# Generated by Django 5.2.8 on 2025-11-26 01:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pagina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_do_site', models.CharField(max_length=100)),
                ('logo_do_site', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('texto_chamada', models.CharField(help_text='Texto principal do banner', max_length=200)),
                ('texto_sobre', models.TextField()),
                ('imagem_sobre', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('endereco', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('whatsapp', models.CharField(max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuração da Página',
                'verbose_name_plural': 'Configurações da Página',
            },
        ),
    ]
