<<<<<<< HEAD
# Generated by Django 5.2.8 on 2025-11-26 20:20
=======
# Generated by Django 5.2.8 on 2025-11-26 14:40
>>>>>>> 904a7e9c2a31ffce4f44465fbbcdd59b3c886f5b

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('mensagem', models.TextField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
